services:
  - type: web
    name: sailus-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CRYPTOBOT_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sailus-db
          property: connectionString